AllCops:
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
    - 'vendor/**/*'
Metrics/LineLength:
  Enabled: false
Metrics/ClassLength:
  CountComments: false
  Max: 150
Metrics/MethodLength:
  CountComments: false
  Max: 20
